### ISSUE TITLE
Support for Django ORM

### ISSUE THREAD

**Issue by j-riebe** [cerbos/query-plan-adapters#47]
I'd like to contribute support for [django](https://djangoproject.com) ORM. 
Take a look at [the fork here](https://github.com/optiscaners/query-plan-adapters/tree/django/django).

The django adapter is heavily inspired by the sqlalchemy adapter.
It passes the pre-defined test suite and adds a test for the nested resource policy (currently missing in the sqlalchemy adapter).

Open Todos:
- [ ] Code-Formatting
- [ ] CI integration
- [ ] Documentation in the root project

**Running locally**
Setting up the environment requires [poetry](https://python-poetry.org/docs/#installation).

Checkout the repo `https://github.com/optiscaners/query-plan-adapters.git` at the branch `django`

To install the environment and run the tests:
```bash
make install runtests
```

or without make:

```bash
poetry install --all-extras
pytest
```

**Comment by charithe** [comment]
Hi. Thanks for building this. It's really cool 🙌🏽 

Instead of being a fork of this repo, I suggest that you make it a repo dedicated to just the Django adapter. We'll be happy to link to it as a community project so that others can discover it. The reason for this is that if we incorporate it into this repo, we'll be responsible for maintaining it and keeping it compatible with Django releases going forward. Unfortunately, we don't have Django expertise in the team to do that at the moment.

**Comment by j-riebe** [comment]
Alright, then lets do it that way 👍 

Thanks for the fast response.

**Comment by charithe** [comment]
Please let us know when it's ready so that we can link to it.
